# Generated by Django 6.0.2 on 2026-03-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0002_alter_event_category_alter_event_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
