# Generated by Django 6.0.2 on 2026-03-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
