# Generated by Django 6.0.2 on 2026-03-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0002_alter_project_options_alter_projectcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
